export const tournament = [
    {
        availability: "Abierto",
        genre: "Femenino",
        image: "images/torneo-fem.avif",
        title: "Copa Verano 2025",
        location: "Chiquinquirá, Camelot",
        date: "15 Jul - 25 Jul",
        income: "300.000",
    },
    {
        availability: "Últimos cupos",
        genre: "Masculino",
        image: "images/torneo-mas.avif",
        title: "Liga Empresarial",
        location: "Chiquinquirá, La Fiera",
        date: "10 Nov - 25 Nov",
        income: "300.000",
    },
    {
        availability: "Finalizado",
        genre: "Mixto",
        image: "images/torneo-mas.avif",
        title: "Torneo Relámpago",
        location: "Chiquinquirá, El Barcelona",
        date: "10 Dic - 10 Dic",
        income: "350.000",
    },
    {
        availability: "Abierto",
        genre: "Masculino",
        image: "images/torneo-mas.avif",
        title: "Copa Oro 2025",
        location: "Tunja, Estadio La Independencia",
        date: "5 Ene - 15 Ene",
        income: "400.000",
    },
    {
        availability: "Próximamente",
        genre: "Femenino",
        image: "images/torneo-fem.avif",
        title: "Liga Femenina Elite",
        location: "Duitama, Estadio Bicentenario",
        date: "1 Feb - 28 Feb",
        income: "350.000",
    },
    {
        availability: "Abierto",
        genre: "Mixto",
        image: "images/torneo-mas.avif",
        title: "Torneo de Invierno",
        location: "Sogamoso, Estadio Luis Antonio Duque",
        date: "15 Mar - 30 Mar",
        income: "320.000",
    },
    {
        availability: "Últimos cupos",
        genre: "Masculino",
        image: "images/torneo-mas.avif",
        title: "Copa Libertadores Local",
        location: "Paipa, Estadio Municipal",
        date: "10 Abr - 25 Abr",
        income: "380.000",
    },
    {
        availability: "Próximamente",
        genre: "Femenino",
        image: "images/torneo-fem.avif",
        title: "Torneo Primavera",
        location: "Tibasosa, Canchas Sintéticas",
        date: "1 May - 15 May",
        income: "300.000",
    },
    {
        availability: "Abierto",
        genre: "Mixto",
        image: "images/torneo-mas.avif",
        title: "Copa Amistad",
        location: "Nobsa, Polideportivo Municipal",
        date: "5 Jun - 20 Jun",
        income: "280.000",
    },
    {
        availability: "Finalizado",
        genre: "Masculino",
        image: "images/torneo-mas.avif",
        title: "Torneo Aniversario",
        location: "Sogamoso, Canchas El Campín",
        date: "15 Ago - 30 Ago",
        income: "320.000",
    },
    {
        availability: "Próximamente",
        genre: "Femenino",
        image: "images/torneo-fem.avif",
        title: "Copa Estrellas",
        location: "Tunja, Canchas La Glorieta",
        date: "10 Sep - 25 Sep",
        income: "350.000",
    },
    {
        availability: "Abierto",
        genre: "Mixto",
        image: "images/torneo-mas.avif",
        title: "Torneo de Cierre de Año",
        location: "Duitama, Canchas El Salitre",
        date: "1 Dic - 15 Dic",
        income: "400.000",
    },
    {
        availability: "Últimos cupos",
        genre: "Masculino",
        image: "images/torneo-mas.avif",
        title: "Copa Navideña",
        location: "Chiquinquirá, Polideportivo",
        date: "15 Dic - 30 Dic",
        income: "450.000",
    }
]